title: OSORI DB
description: Initial Github Pages for OSORI DB
theme: just-the-docs

url: https://osori-db.github.io

aux_links:
  Template Repository: https://github.com/osori-db/osori-db.github.io

lang: ["en", "ko"]
defaultLang: en
languageNames:
  ko: Korean
  en: English
